export const SKILL_GROUPS = [
  {
    key: "frontend",
    technologies: [
      "HTML5",
      "CSS3",
      "JavaScript",
      "TypeScript",
      "React.js",
      "React Router",
      "TanStack Query",
      "Redux Toolkit",
      "Zustand",
      "Next.js",
      "React Hook Form",
      "Zod",
      "Vite",
      "TanStack Start",
      "Tailwind CSS",
      "MUI Components",
      "Framer Motion",
      "React Testing Library",
      "Axios",
      "Auth0",
      "Better Auth",
    ],
  },
  {
    key: "backend",
    technologies: [
      "Node.js",
      "Express.js",
      "Prisma ORM",
      "MySQL",
      "PostgreSQL",
      "REST APIs",
      "GraphQL",
      "JWT Authentication",
      "Vitest",
    ],
  },
  {
    key: "tools",
    technologies: [
      "VSCode",
      "Git",
      "GitHub",
      "Insomnia",
      "Postman",
      "Notion",
      "Docker",
      "AWS S3",
      "AWS EC2",
      "AWS SES",
    ],
  },
] as const;
