export const SKILL_GROUPS = [
  {
    key: "frontend",
    technologies: [
      "HTML5",
      "CSS3",
      "JavaScript",
      "TypeScript",
      "React",
      "React Router",
      "TanStack Query",
      "Redux Toolkit",
      "Zustand",
      "Next.js",
      "React Hook Form",
      "Zod",
      "Vite",
      "TanStack Start",
      "Tailwind CSS",
      "MUI Components",
      "Motion",
    ],
  },
  {
    key: "testingAndIntegration",
    technologies: [
      "Vitest",
      "Playwright",
      "React Testing Library",
      "REST APIs",
      "Axios",
      "Auth0",
      "Stripe",
      "Better Auth"
    ],
  },
  {
    key: "backendAndData",
    technologies: [
      "Node.js",
      "Express.js",
      "Prisma ORM",
      "MySQL",
      "PostgreSQL",
      "JWT Authentication",
      "OAuth 2.0",
      "REST APIs",
    ],
  },
  {
    key: "toolsAndDelivery",
    technologies: [
      "Git",
      "GitHub",
      "Github Actions (CI)",
      "Postman",
      "CI/CD Pipelines",
      "Docker",
      "Figma",
      "AWS (S3, EC2, SES)",
    ],
  },
  {
    key: "developmentApproach",
    technologies: [
      "Agentic development workflows",
      "AI Coding Orchestration",
      "Specification-Driven Development (SDD)",
      "Test-Driven Development (TDD)",
      "Domain-Driven Design (DDD)",
      "Agile Methodologies",
      "Soft Systems Methodology (SSM)",
      "Requirement Analysis",
    ],
  },
  
] as const;
